author:
  name: Eliezer Oliveira
  email: eliezerreis@gmail.com

info:
  app:
    name: "accounts"
    description: "EzBank Accounts Application"
    version: 0.0.1

server:
  port: 8090

spring:
  application:
    name: "accounts"
  datasource:
    driver-class-name: org.h2.Driver
    url: "{cipher}4eec0fafbf364408e4b12a6cc55a9ecfde2818c031430af65646265564c4d4a266a794b33c1c4e20e3d209abd19f064392f8a32e4032db7b502c57badc6e416871471efc9512359ed2a24213ea7510214f493dd21b3f8f13aa0b974105495c1d"
    username: "{cipher}dd2b11be0b78a3f276e6751b946f3498978f74c4438e9932feffc0b95d993eb5"
    password: "{cipher}7749443b975ed724d604d01b351b0e51b99b7577b345d4b8925f407f09fdb009"
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
  cloud:
    function:
      definition: processEmail
    stream:
      default:
        consumer:
          queue-name-group-only: true
        producer:
          exchange-type: topic
      bindings:
        welcome-email:
          destination: accounts-events
        welcome-sms:
          destination: accounts-events
        processEmail-in-0:
          destination: notifications-events
          group: welcome-email-sent
      rabbit:
        bindings:
          welcome-email:
            producer:
              routing-key: accounts-events.welcome-email
          welcome-sms:
            producer:
              routing-key: accounts-events.welcome-sms
          processEmail-in-0:
            consumer:
              dead-letter-exchange: notifications-events.dlx
              dead-letter-routing-key: notifications-events.welcome-email-sent.dlq
              auto-bind-dlq: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    connection-timeout: 20s

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8081/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"