author:
  name: Eliezer Oliveira
  email: eliezerreis@gmail.com

server:
  port: 8080

spring:
  could:
    gateway:
      discovery:
        locator:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      access: unrestricted

info:
  app:
    name: 'apigateway'
    description: 'API Gateway'
    version: 0.0.1