author:
  name: Eliezer Oliveira
  email: eliezerreis@gmail.com

server:
  port: 8080

spring:
  application:
    name: "apigateway"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: "http://localhost:8081/eureka/"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true

info:
  app:
    name: "apigateway"
    description: "API Gateway"
    version: 0.0.1

logging:
  level:
    com:
      ezbank:
        apigateway: DEBUG