author:
  name: Eliezer Oliveira
  email: eliezerreis@gmail.com

server:
  port: 8080

spring:
  application:
    name: apigateway

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
    gateway:
      access: unrestricted
  info:
    env:
      enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true

info:
  app:
    name: 'apigateway'
    description: 'API Gateway'
    version: 0.0.1

logging:
  level:
    com:
      ezbank:
        apigateway: DEBUG